### ISSUE TITLE
npm install issues without specific npm version

### ISSUE THREAD

**Issue by Kazilico** [18F/openopps-platform#1133]
Hey all -- I was trying to set up this project by building from source, and I ran into a few issues.  I will try to provide details together in this ticket. Not sure if this is tied together in some way or independent. 

When I ran `npm install`, I got this error. 
```
> midas@0.7.6 build /Users/jc/Projects/midas
> $npm_package_config_grunt build

sh: ./node_modules/sails/node_modules/.bin/grunt: No such file or directory

npm ERR! midas@0.7.6 build: `$npm_package_config_grunt build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the midas@0.7.6 build script.
npm ERR! This is most likely a problem with the midas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $npm_package_config_grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls midas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/jc/.nvm/v0.10.40/bin/node" "/Users/jc/.nvm/v0.10.40/bin/npm" "run" "build"
npm ERR! cwd /Users/jc/Projects/midas
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jc/Projects/midas/npm-debug.log
npm ERR! not ok code 0

npm ERR! midas@0.7.6 install: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midas@0.7.6 install script.
npm ERR! This is most likely a problem with the midas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls midas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/jc/.nvm/v0.10.40/bin/node" "/Users/jc/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /Users/jc/Projects/midas
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jc/Projects/midas/npm-debug.log
npm ERR! not ok code 0
``` 

That seemed to be resolved by `npm install grunt-cli`.
Question 1 - Should I submit a pull request to update package.json? (Please advise. I am not confident this is a fix -- you all would know better.)

But then, `npm run init` ended up in this error: 
```
Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jc/Projects/midas/node_modules/sails/lib/hooks/session/index.js:10:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at hooks (/Users/jc/Projects/midas/node_modules/sails/lib/app/configuration/index.js:54:28)
    at Function.reduce (/Users/jc/Projects/midas/node_modules/lodash/dist/lodash.js:3735:25)
    at Configuration.defaultConfig (/Users/jc/Projects/midas/node_modules/sails/lib/app/configuration/index.js:53:18)
    at Configuration.bound [as defaults] (/Users/jc/Projects/midas/node_modules/lodash/dist/lodash.js:729:21)
    at Array.async.auto.mixinDefaults [as 1] (/Users/jc/Projects/midas/node_modules/sails/lib/app/configuration/load.js:136:41)

npm ERR! midas@0.7.6 init: `node test/init/init/init.test.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the midas@0.7.6 init script.
npm ERR! This is most likely a problem with the midas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/init/init/init.test.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls midas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/jc/.nvm/v0.10.40/bin/node" "/Users/jc/.nvm/v0.10.40/bin/npm" "run" "init"
npm ERR! cwd /Users/jc/Projects/midas
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jc/Projects/midas/npm-debug.log
npm ERR! not ok code 0
```

Question 2 - Any idea on how to get passed this error? I tried `npm install connect`, but that didn't seem to work. 

Thanks.

**Comment by rogeruiz** [comment]
Hey @Kazilico, Sorry to hear that you're having issues getting the project running from source. In order to answer your *second question a bit better*, could you please post the following file here? `/Users/jc/Projects/midas/npm-debug.log` Thanks!

*An answer to the first question*, I believe that the specific error here is related to your version of `npm` that ships with `node@0.10.40`. Try following [these instructions to update your installation of `npm`](https://docs.npmjs.com/getting-started/installing-node#updating-npm). You want to make sure you're installing the version [that is described in the `engines` hash of the `package.json` here](https://github.com/18F/midas/blob/dev/package.json#L96-L99).

From the output you pasted above, I believe that the `node_modules` packages never actually installed properly. *Once you've upgraded `npm` using the instructions above*, make sure that you delete your `node_modules` directory in the project folder.

Example:

```
% rm -rvf /Users/jc/Projects/midas/node_modules
```

**Comment by Kazilico** [comment]
Hey @rogeruiz, thanks for your time. Here is the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/jc/.nvm/v0.10.40/bin/npm', 'run', 'init' ]
2 info using npm@3.4.0
3 info using node@v0.10.40
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle midas@0.7.6~preinit: midas@0.7.6
6 silly lifecycle midas@0.7.6~preinit: no script for preinit, continuing
7 info lifecycle midas@0.7.6~init: midas@0.7.6
8 verbose lifecycle midas@0.7.6~init: unsafe-perm in lifecycle true
9 verbose lifecycle midas@0.7.6~init: PATH: /Users/jc/.nvm/v0.10.40/lib/node_modules/npm/bin/node-gyp-bin:/Users/jc/Projects/midas/node_modules/.bin:/Users/jc/.nvm/v0.10.40/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/jc/.rbenv/shims:/Users/jc/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
10 verbose lifecycle midas@0.7.6~init: CWD: /Users/jc/Projects/midas
11 silly lifecycle midas@0.7.6~init: Args: [ '-c', 'node test/init/init/init.test.js' ]
12 silly lifecycle midas@0.7.6~init: Returned: code: 8  signal: null
13 info lifecycle midas@0.7.6~init: Failed to exec init script
14 verbose stack Error: midas@0.7.6 init: `node test/init/init/init.test.js`
14 verbose stack Exit status 8
14 verbose stack     at EventEmitter.<anonymous> (/Users/jc/.nvm/v0.10.40/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at EventEmitter.emit (events.js:98:17)
14 verbose stack     at ChildProcess.<anonymous> (/Users/jc/.nvm/v0.10.40/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at ChildProcess.emit (events.js:98:17)
14 verbose stack     at maybeClose (child_process.js:766:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
15 verbose pkgid midas@0.7.6
16 verbose cwd /Users/jc/Projects/midas
17 error Darwin 15.0.0
18 error argv "node" "/Users/jc/.nvm/v0.10.40/bin/npm" "run" "init"
19 error node v0.10.40
20 error npm  v3.4.0
21 error code ELIFECYCLE
22 error midas@0.7.6 init: `node test/init/init/init.test.js`
22 error Exit status 8
23 error Failed at the midas@0.7.6 init script 'node test/init/init/init.test.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the midas package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node test/init/init/init.test.js
23 error You can get their info via:
23 error     npm owner ls midas
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
 ```

As to the other issue, I've updated my `npm`, but that brings me to node version `0.10.40`, but my `npm` is now at `3.4.0`, much higher than the version [that is described in the `engines` hash of the `package.json` here.] (https://github.com/18F/midas/blob/dev/package.json#L96-L99)

I've looked for an answer as to how to run an older version of `npm`, but haven't found an answer that works. I know that I can specify the `nvm` that I use with `nvm alias default` but can't find something similar for `npm`.

Thanks.

**Comment by rogeruiz** [comment]
Hey @Kazilico, thanks for the log file. I will look it over and see if I can reproduce the error locally.

Try running this command to install a particular version of `npm`:

```
 % sudo npm install --global npm@2.1.x
```

That should install `2.1.18` which should be alright. Once you have that installed, try deleting your `node_modules` directory and running `npm install` again. If this works out, we'll have to update the `INSTALL` documentation to show how to install the particular versions required by the project.

**Comment by Kazilico** [comment]
Hey @rogeruiz, that did it. Successful `npm install`! Thanks for that.

**Comment by rogeruiz** [comment]
Great. I'll rename this issue and keep it open to help get the `INSTALL.md` up to date with this new information. Thanks, @Kazilico!
