### ISSUE TITLE
error turning a model into an object...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1171]
this might be some issue with my local install, but tracking it here since others might run into it later

```
$  git clone git@github.com:18F/openopps-platform.git
$  cd openopps-platform/
$  npm install
$  npm run migrate
$  npm run init
$ npm run demo

> openopps-platform@0.8.0-rc4 demo /Users/sarahallen/src/18F/openopps-platform
> mocha test/test.upstart.js --development --recursive test/demo



lifting sails: env=development
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/application.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/assets.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/bootstrap.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/connections.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/controllers.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/csrf.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/email.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/globals.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/http.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/io.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/models.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/policies.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/routes.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/session.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/env/development.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/settings/analytics.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/settings/auth.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/settings/sources.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/settings/tags.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/sockets.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/version.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/views.js
Loading...  /Users/sarahallen/src/18F/openopps-platform/config/env/development.js
  demo:
user created: Tammy Craig
user created: Pran Mhasalkar
user created: Alan Barret
user created: Janice Thompson
user created: Clay Smithson
user created: Lucia Esperanza
user created: Dante Francis
user created: Serena Chao
user created: Jason Xui
user created: Sally Wilson
user created: Robert Simmons
user created: Tanya de la Rocha
    ✓ users (6429ms)
    ✓ tags (1932ms)
    1) user tags
processComment
== Writing { type: 'skill',
  name: 'Writing',
  obj: 
   { type: 'skill',
     name: 'Writing',
     id: 21,
     createdAt: '2015-12-02T18:35:32.000Z',
     updatedAt: '2015-12-02T18:35:32.000Z',
     deletedAt: null,
     data: null },
  id: 21 }
== Social Media { type: 'skill',
  name: 'Social Media',
  obj: 
   { type: 'skill',
     name: 'Social Media',
     id: 22,
     createdAt: '2015-12-02T18:35:32.000Z',
     updatedAt: '2015-12-02T18:35:32.000Z',
     deletedAt: null,
     data: null },
  id: 22 }
    2) projects
error: Sending 500 ("Server Error") response: 
 Error: There was an error turning the model into an object.
    at new module.exports (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/toObject.js:56:15)
    at prototypeFns.toObject (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:30:14)
    at Array.async.auto.updateRecord [as 1] (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:81:32)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at new module.exports (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:52:9)
    at prototypeFns.save (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:34:14)
    at module.exports.disable (/Users/sarahallen/src/18F/openopps-platform/api/controllers/UserController.js:285:21)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at requireUserId (/Users/sarahallen/src/18F/openopps-platform/api/policies/requireUserId.js:9:3)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at requireId (/Users/sarahallen/src/18F/openopps-platform/api/policies/requireId.js:9:3)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at authenticated (/Users/sarahallen/src/18F/openopps-platform/api/policies/authenticated.js:10:12)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at /Users/sarahallen/src/18F/openopps-platform/api/policies/passport.js:34:7
    at SessionStrategy.strategy.pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/strategies/session.js:61:12
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/authenticator.js:333:31)
    at deserialized (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/authenticator.js:345:7)
    at /Users/sarahallen/src/18F/openopps-platform/api/services/passport.js:417:5
    at wrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at _normalizeCallback.callback.success (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at returnResults (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:180:9)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:91:16
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:77:45
    at wrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at _normalizeCallback.callback.success (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/lib/adapter.js:1162:16
    at Cursor.attachRecords (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/waterline-cursor/cursor/cursor.js:117:10)
    at afterPopulateBuffers (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/waterline-cursor/cursor/cursor.js:55:10)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/lib/adapter.js:789:15
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:451:17
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:441:17
    at _each (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:46:13)
    at Object.taskComplete (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:363:15) { [Error: There was an error turning the model into an object.]
  message: 'There was an error turning the model into an object.',
  data: 
   { '0': 
      { '0': [Circular],
        passports: [],
        badges: [],
        tags: [],
        username: 'kids@test.gov',
        name: 'Tammy Craig',
        title: 'Social Media Director',
        bio: null,
        photoId: null,
        photoUrl: null,
        isAdmin: false,
        disabled: true,
        passwordAttempts: 0,
        completedTasks: 0,
        id: 1,
        createdAt: Wed Dec 02 2015 10:35:25 GMT-0800 (PST),
        updatedAt: Wed Dec 02 2015 10:35:26 GMT-0800 (PST) },
     tags: [],
     username: 'kids@test.gov',
     name: 'Tammy Craig',
     title: 'Social Media Director',
     bio: null,
     photoId: null,
     photoUrl: null,
     isAdmin: false,
     disabled: true,
     passwordAttempts: 0,
     completedTasks: 0,
     id: 1,
     createdAt: Wed Dec 02 2015 10:35:25 GMT-0800 (PST),
     updatedAt: Wed Dec 02 2015 10:35:26 GMT-0800 (PST) } }
error: Server Error:
error: Error: There was an error turning the model into an object.
    at new module.exports (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/toObject.js:56:15)
    at prototypeFns.toObject (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:30:14)
    at Array.async.auto.updateRecord [as 1] (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:81:32)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at new module.exports (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:52:9)
    at prototypeFns.save (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:34:14)
    at module.exports.disable (/Users/sarahallen/src/18F/openopps-platform/api/controllers/UserController.js:285:21)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at requireUserId (/Users/sarahallen/src/18F/openopps-platform/api/policies/requireUserId.js:9:3)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at requireId (/Users/sarahallen/src/18F/openopps-platform/api/policies/requireId.js:9:3)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at authenticated (/Users/sarahallen/src/18F/openopps-platform/api/policies/authenticated.js:10:12)
    at routeTargetFnWrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/lib/router/bind.js:186:7
    at /Users/sarahallen/src/18F/openopps-platform/api/policies/passport.js:34:7
    at SessionStrategy.strategy.pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/strategies/session.js:61:12
    at pass (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/authenticator.js:333:31)
    at deserialized (/Users/sarahallen/src/18F/openopps-platform/node_modules/passport/lib/authenticator.js:345:7)
    at /Users/sarahallen/src/18F/openopps-platform/api/services/passport.js:417:5
    at wrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at _normalizeCallback.callback.success (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at returnResults (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:180:9)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:91:16
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:77:45
    at wrapper (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at _normalizeCallback.callback.success (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/lib/adapter.js:1162:16
    at Cursor.attachRecords (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/waterline-cursor/cursor/cursor.js:117:10)
    at afterPopulateBuffers (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/waterline-cursor/cursor/cursor.js:55:10)
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/lib/adapter.js:789:15
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:451:17
    at /Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:441:17
    at _each (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:46:13)
    at Object.taskComplete (/Users/sarahallen/src/18F/openopps-platform/node_modules/sails-postgresql/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:363:15) { [Error: There was an error turning the model into an object.]
  message: 'There was an error turning the model into an object.',
  data: 
   { '0': 
      { '0': [Circular],
        passports: [],
        badges: [],
```

**Comment by rogeruiz** [comment]
Looks like this could be related to #1175 :+1: 

```sh
    at module.exports.disable (/Users/sarahallen/src/18F/openopps-platform/api/controllers/UserController.js:285:21
```

https://github.com/18F/openopps-platform/blob/dev/api/controllers/UserController.js#L279-L298

I'll leave this open for now, but hopefully these two issues can be closed with the same PR. :dancer:
